version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mohitmolela@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  landing-page:
    # image: mohitkumhar/intelligent-business-agent-web:latest
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    container_name: landing-page
    restart: always
    ports:
      - "5173:5173"

    volumes:
      - ./landing-page:/app
      - /app/node_modules

    environment:
      - VITE_API_URL=http://localhost:8000
      - DATABASE_URL=postgresql://admin:root@db:5432/test_db
      - ENCRYPTION_SECRET=12345678901234567890123456789012
      - NEXTAUTH_URL=http://localhost:5173
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:5173

    depends_on:
      - backend
      - db

    stdin_open: true
    tty: true

  backend:
    # image: mohitkumhar/intelligent-business-agent:latest
    build:
      context: ./agent_code
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./agent_code:/app
      - ./logs:/app/logs
    env_file:
      - ./.env
    depends_on:
      - db

    # promptail and loki configuration
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log/app
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki

volumes:
  pgdata:
