/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDecisionsRouteImport } from './routes/dashboard/decisions'
import { Route as DashboardDataRouteImport } from './routes/dashboard/data'
import { Route as DashboardBusinessHealthRouteImport } from './routes/dashboard/business-health'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutSlugRouteImport } from './routes/_layout/$slug'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as HealthzServerRouteImport } from './routes/healthz'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDecisionsRoute = DashboardDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessHealthRoute = DashboardBusinessHealthRouteImport.update({
  id: '/business-health',
  path: '/business-health',
  getParentRoute: () => DashboardRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlugRoute = LayoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const HealthzServerRoute = HealthzServerRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/$slug': typeof LayoutSlugRoute
  '/about': typeof LayoutAboutRoute
  '/dashboard/business-health': typeof DashboardBusinessHealthRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/decisions': typeof DashboardDecisionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/$slug': typeof LayoutSlugRoute
  '/about': typeof LayoutAboutRoute
  '/dashboard/business-health': typeof DashboardBusinessHealthRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/decisions': typeof DashboardDecisionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_layout/$slug': typeof LayoutSlugRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/dashboard/business-health': typeof DashboardBusinessHealthRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/decisions': typeof DashboardDecisionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$slug'
    | '/about'
    | '/dashboard/business-health'
    | '/dashboard/data'
    | '/dashboard/decisions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/$slug'
    | '/about'
    | '/dashboard/business-health'
    | '/dashboard/data'
    | '/dashboard/decisions'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/dashboard'
    | '/_layout/$slug'
    | '/_layout/about'
    | '/dashboard/business-health'
    | '/dashboard/data'
    | '/dashboard/decisions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/healthz': typeof HealthzServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRoutesByTo {
  '/healthz': typeof HealthzServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/healthz': typeof HealthzServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/healthz' | '/sitemap.xml'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/healthz' | '/sitemap.xml'
  id: '__root__' | '/healthz' | '/sitemap.xml'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  HealthzServerRoute: typeof HealthzServerRoute
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/decisions': {
      id: '/dashboard/decisions'
      path: '/decisions'
      fullPath: '/dashboard/decisions'
      preLoaderRoute: typeof DashboardDecisionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-health': {
      id: '/dashboard/business-health'
      path: '/business-health'
      fullPath: '/dashboard/business-health'
      preLoaderRoute: typeof DashboardBusinessHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$slug': {
      id: '/_layout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof LayoutSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutSlugRoute: typeof LayoutSlugRoute
  LayoutAboutRoute: typeof LayoutAboutRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSlugRoute: LayoutSlugRoute,
  LayoutAboutRoute: LayoutAboutRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardRouteChildren {
  DashboardBusinessHealthRoute: typeof DashboardBusinessHealthRoute
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardDecisionsRoute: typeof DashboardDecisionsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessHealthRoute: DashboardBusinessHealthRoute,
  DashboardDataRoute: DashboardDataRoute,
  DashboardDecisionsRoute: DashboardDecisionsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  HealthzServerRoute: HealthzServerRoute,
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
